services:
  - type: web
    name: bluespace-restaurant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bluespace-db
          property: connectionString

databases:
  - name: bluespace-db
    databaseName: bluespace
    user: bluespace_user 